spring:
  main:
    allow-circular-references: true
  datasource:
    password: qwert1234
    username: zhong
    url: jdbc:mysql://192.168.123.56:13306/yeb?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池名字
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认（60000）10分钟
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间 0表示永久，默认（1800000）30分钟
      max-lifetime: 1800000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    # 超时时间
    connect-timeout: 10000ms
    host: 192.168.123.56
    port: 16379
    database: 0
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5


  profiles:
    active:

server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxxx.yebserver.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.xxxx.yebserver.mapper: debug

jwt:
  tokenHeader: Authorization
  secret: UveTNxMFoy2dyqNwqDDRunv4832kQ4yFdGWtQNt+hhk=
  expiration: 604800
  tokenHead: Bearer


secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/**
      - /swagger-resources/**
      - /v3/api-docs/**
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**
      - /login
      - /logout
      - /captcha